/**
 * Auto-layout integration with the `bpmn-auto-layout` library
 * (github:datakurre/bpmn-auto-layout).
 *
 * The library is XML-in / XML-out: it takes BPMN 2.0 XML and returns the
 * same model with freshly generated diagram interchange (DI).  This module
 * bridges it to a live bpmn-js modeler:
 *
 *  1. Export the modeler's XML and run the library on it (or on a pruned
 *     copy that only contains a subset of elements).
 *  2. Read the generated DI (shape bounds, edge waypoints, label bounds).
 *  3. Apply that DI back to the modeler through `modeling` commands,
 *     wrapped in a single compound command so the whole layout is one
 *     undo step in `bpmn_history`.
 *
 * Subset layout is supported in two flavours:
 *  - `scopeElementId`: re-layout one Participant or SubProcess (and its
 *    contents).  Positions are taken from a full-diagram layout and
 *    translated so the scope element keeps its current top-left corner.
 *  - `elementIds`: re-layout an arbitrary set of sibling flow elements.
 *    The elements are extracted into a standalone process, laid out on
 *    their own and translated so the set keeps its current top-left corner.
 *
 * In both cases connections that cross the subset boundary are re-routed
 * with bpmn-js' own `modeling.layoutConnection()`.
 */

import { layoutProcessWithDiagnostics, type LayoutWarning } from 'bpmn-auto-layout';
import camundaModdle from 'camunda-bpmn-moddle/resources/camunda.json';
import type { DiagramState } from './types';
import { getService } from './bpmn-types';
import { buildSubsetXml, prepareXml } from './auto-layout-input';

// ── Types ──────────────────────────────────────────────────────────────────

export interface Point {
  x: number;
  y: number;
}

export interface Bounds extends Point {
  width: number;
  height: number;
}

interface ShapeLayout {
  bounds: Bounds;
  label?: Bounds;
}

interface EdgeLayout {
  waypoints: Point[];
  label?: Bounds;
}

/** DI generated by the layout library, keyed by BPMN element ID. */
export interface LayoutResult {
  shapes: Map<string, ShapeLayout>;
  edges: Map<string, EdgeLayout>;
  warnings: LayoutWarning[];
}

export interface AutoLayoutOptions {
  /** Re-layout only this Participant or SubProcess (and its contents). */
  scopeElementId?: string;
  /** Re-layout only these sibling flow elements (boundary events follow their hosts). */
  elementIds?: string[];
  /** Elements that must keep their current position. */
  pinnedElementIds?: Set<string>;
}

export interface AutoLayoutResult {
  repositionedCount: number;
  reroutedCount: number;
  warnings: LayoutWarning[];
}

// ── Library invocation ─────────────────────────────────────────────────────

/** Run the layout library on BPMN XML, preserving Camunda extension attributes. */
export async function runAutoLayout(
  xml: string
): Promise<{ xml: string; warnings: LayoutWarning[] }> {
  return layoutProcessWithDiagnostics(xml, {
    moddleExtensions: { camunda: camundaModdle },
    lenientFlowValidation: true,
  });
}

/** Parse library output XML into a lookup of shape/edge DI by element ID. */
async function readLayout(
  moddle: any,
  xml: string,
  warnings: LayoutWarning[]
): Promise<LayoutResult> {
  const { rootElement: definitions } = await moddle.fromXML(xml);
  const shapes = new Map<string, ShapeLayout>();
  const edges = new Map<string, EdgeLayout>();

  for (const diagram of definitions.diagrams || []) {
    for (const di of diagram.plane?.planeElement || []) {
      const id = di.bpmnElement?.id;
      if (!id) continue;
      const label = di.label?.bounds ? toBounds(di.label.bounds) : undefined;
      if (di.$type === 'bpmndi:BPMNShape' && di.bounds) {
        shapes.set(id, { bounds: toBounds(di.bounds), label });
      } else if (di.$type === 'bpmndi:BPMNEdge' && di.waypoint?.length) {
        edges.set(id, { waypoints: di.waypoint.map((p: Point) => ({ x: p.x, y: p.y })), label });
      }
    }
  }
  return { shapes, edges, warnings };
}

function toBounds(b: Bounds): Bounds {
  return { x: b.x, y: b.y, width: b.width, height: b.height };
}

// ── Applying DI to the modeler ─────────────────────────────────────────────

const APPLY_COMMAND = 'bpmn-mcp.applyAutoLayout';

interface ApplyContext {
  layout: LayoutResult;
  include: (el: any) => boolean;
  offset: Point;
  pinned: Set<string>;
  result: { repositionedCount: number; reroutedCount: number };
}

/**
 * The BPMN ID of a diagram element.  Layout DI is keyed by BPMN ID, which
 * can differ from the element registry ID (e.g. for participants and lanes).
 */
function bpmnId(el: any): string {
  return el.businessObject?.id ?? el.id;
}

function isConnection(el: any): boolean {
  return !!el.waypoints;
}

function isLabel(el: any): boolean {
  return el.type === 'label';
}

function depth(el: any): number {
  let d = 0;
  for (let p = el.parent; p; p = p.parent) d++;
  return d;
}

/** Register (once per modeler) the compound command that applies a layout. */
function ensureApplyCommand(modeler: any): void {
  const commandStack = getService(modeler, 'commandStack') as any;
  if (commandStack._getHandler?.(APPLY_COMMAND)) return;

  const modeling = getService(modeler, 'modeling') as any;
  const registry = getService(modeler, 'elementRegistry') as any;

  commandStack.registerHandler(APPLY_COMMAND, function ApplyLayoutHandler(this: any) {
    this.preExecute = (ctx: ApplyContext) => applyLayoutCommands(ctx, modeling, registry);
    this.execute = () => [];
    this.revert = () => [];
  });
}

function round(v: number): number {
  return Math.round(v);
}

function shift(p: Point, offset: Point): Point {
  return { x: round(p.x + offset.x), y: round(p.y + offset.y) };
}

function applyLayoutCommands(ctx: ApplyContext, modeling: any, registry: any): void {
  const all: any[] = registry.getAll();

  // Remember label offsets relative to their owners before anything moves.
  const labelOffsets = new Map<string, Point>();
  for (const el of all) {
    if (el.label && !isConnection(el)) {
      labelOffsets.set(el.id, { x: el.label.x - el.x, y: el.label.y - el.y });
    }
  }

  const shapes = selectShapes(all, ctx);
  for (const shape of shapes) applyShape(shape, ctx, modeling);
  for (const shape of shapes) applyShapeLabel(shape, ctx, modeling, labelOffsets.get(shape.id));

  const movedIds = new Set(shapes.map((s) => s.id));
  for (const conn of all.filter(isConnection)) applyConnection(conn, ctx, modeling, movedIds);

  // bpmn-js re-derives lane membership (flowNodeRef) after every nested
  // move/resize, i.e. from intermediate geometry while lanes and their
  // contents are only partly placed.  Recompute it once from the final
  // geometry, which the layout engine derived from the original membership.
  const lanes = all.filter((el) => el.type === 'bpmn:Lane');
  if (lanes.length > 0 && shapes.length > 0) modeling.updateLaneRefs([], lanes);
}

/** Shapes to lay out: containers before their children, boundary events after hosts. */
function selectShapes(all: any[], ctx: ApplyContext): any[] {
  const { layout, include, pinned } = ctx;
  return all
    .filter(
      (el) =>
        !isConnection(el) &&
        !isLabel(el) &&
        el.parent &&
        include(el) &&
        !pinned.has(el.id) &&
        layout.shapes.has(bpmnId(el))
    )
    .sort((a, b) => {
      const ab = a.type === 'bpmn:BoundaryEvent' ? 1 : 0;
      const bb = b.type === 'bpmn:BoundaryEvent' ? 1 : 0;
      return ab - bb || depth(a) - depth(b);
    });
}

function applyShape(shape: any, ctx: ApplyContext, modeling: any): void {
  const target = ctx.layout.shapes.get(bpmnId(shape))!.bounds;
  const { x, y } = shift(target, ctx.offset);
  const sizeChanged = target.width !== shape.width || target.height !== shape.height;
  const moved = x !== shape.x || y !== shape.y;
  if (!moved && !sizeChanged) return;

  // Children are placed after their container, so moving the container
  // along with its children is fine; connections are routed afterwards.
  const hints = { layout: false, autoResize: false };
  if (moved) {
    modeling.moveShape(shape, { x: x - shape.x, y: y - shape.y }, null, undefined, hints);
  }
  if (sizeChanged) {
    modeling.resizeShape(shape, { x, y, width: target.width, height: target.height }, null, hints);
  }
  ctx.result.repositionedCount++;
}

/** Place a shape's external label where the library put it, or keep its relative offset. */
function applyShapeLabel(shape: any, ctx: ApplyContext, modeling: any, rel?: Point): void {
  if (!shape.label) return;
  const layoutLabel = ctx.layout.shapes.get(bpmnId(shape))!.label;
  if (layoutLabel) {
    moveLabelTo(modeling, shape.label, shift(layoutLabel, ctx.offset));
  } else if (rel) {
    moveLabelTo(modeling, shape.label, { x: shape.x + rel.x, y: shape.y + rel.y });
  }
}

/**
 * Take library waypoints when both ends were laid out together; otherwise
 * let bpmn-js re-route connections attached to moved shapes.
 */
function applyConnection(conn: any, ctx: ApplyContext, modeling: any, movedIds: Set<string>): void {
  const { include, pinned, offset } = ctx;
  const edge = ctx.layout.edges.get(bpmnId(conn));
  const endsPinned = pinned.has(conn.source?.id) || pinned.has(conn.target?.id);

  if (edge && include(conn) && !endsPinned) {
    modeling.updateWaypoints(
      conn,
      edge.waypoints.map((p) => shift(p, offset))
    );
    if (conn.label && edge.label) moveLabelTo(modeling, conn.label, shift(edge.label, offset));
    ctx.result.reroutedCount++;
  } else if (movedIds.has(conn.source?.id) || movedIds.has(conn.target?.id)) {
    // Empty waypoints make the layouter dock on the (moved) element
    // centres instead of the stale first/last waypoints.
    modeling.layoutConnection(conn, { waypoints: [] });
    ctx.result.reroutedCount++;
  }
}

function moveLabelTo(modeling: any, label: any, target: Point): void {
  const dx = round(target.x) - label.x;
  const dy = round(target.y) - label.y;
  if (dx !== 0 || dy !== 0) modeling.moveShape(label, { x: dx, y: dy }, null, undefined, {});
}

/**
 * Collect the IDs of `root` and all its descendants in the element tree.
 * In diagram-js, `children` also contains connections and labels.
 */
function collectDescendantIds(root: any): Set<string> {
  const ids = new Set<string>();
  const visit = (el: any): void => {
    ids.add(el.id);
    for (const child of el.children || []) visit(child);
    for (const attacher of el.attachers || []) visit(attacher);
  };
  visit(root);
  return ids;
}

/** Bounding box (top-left) of the given shapes in the modeler. */
function topLeftOf(shapes: any[]): Point {
  return {
    x: Math.min(...shapes.map((s) => s.x)),
    y: Math.min(...shapes.map((s) => s.y)),
  };
}

function layoutTopLeft(layout: LayoutResult, ids: Iterable<string>): Point | undefined {
  let x = Infinity;
  let y = Infinity;
  for (const id of ids) {
    const s = layout.shapes.get(id);
    if (!s) continue;
    x = Math.min(x, s.bounds.x);
    y = Math.min(y, s.bounds.y);
  }
  return Number.isFinite(x) ? { x, y } : undefined;
}

// ── Public entry point ─────────────────────────────────────────────────────

/**
 * Lay out a diagram (or a subset of it) with bpmn-auto-layout and apply
 * the result to the diagram's modeler as a single undoable command.
 */
export async function autoLayoutDiagram(
  diagram: DiagramState,
  options: AutoLayoutOptions = {}
): Promise<AutoLayoutResult> {
  const modeler = diagram.modeler;
  const registry = getService(modeler, 'elementRegistry') as any;
  const moddle = getService(modeler, 'moddle') as any;
  const { xml } = await modeler.saveXML({ format: false });

  let include: (el: any) => boolean = () => true;
  let offset: Point = { x: 0, y: 0 };
  let layout: LayoutResult;

  if (options.elementIds && options.elementIds.length > 0) {
    const elements = options.elementIds.map((id) => registry.get(id)).filter(Boolean);
    const ids = new Set(elements.map(bpmnId));
    const subsetXml = await buildSubsetXml(moddle, xml, ids);
    const out = await runAutoLayout(subsetXml);
    layout = await readLayout(moddle, out.xml, out.warnings);

    const shapes = registry
      .getAll()
      .filter((el: any) => !isConnection(el) && !isLabel(el) && ids.has(bpmnId(el)));
    const current = topLeftOf(shapes);
    const laid = layoutTopLeft(layout, ids);
    if (laid) offset = { x: current.x - laid.x, y: current.y - laid.y };
    include = (el) => layout.shapes.has(bpmnId(el)) || layout.edges.has(bpmnId(el));
  } else {
    const out = await runAutoLayout(await prepareXml(moddle, xml));
    layout = await readLayout(moddle, out.xml, out.warnings);

    const scope = options.scopeElementId ? registry.get(options.scopeElementId) : undefined;
    // A root element (e.g. the Process of a non-collaboration diagram) has
    // no shape of its own: scoping to it is the same as a full layout.
    if (scope?.parent) {
      const laid = layout.shapes.get(bpmnId(scope));
      if (!laid) throw new Error(`Scope element '${options.scopeElementId}' was not laid out`);
      const scopeIds = collectDescendantIds(scope);
      offset = { x: scope.x - laid.bounds.x, y: scope.y - laid.bounds.y };
      include = (el) => scopeIds.has(el.id);
    }
  }

  ensureApplyCommand(modeler);
  const ctx: ApplyContext = {
    layout,
    include,
    offset,
    pinned: options.pinnedElementIds ?? new Set(),
    result: { repositionedCount: 0, reroutedCount: 0 },
  };
  (getService(modeler, 'commandStack') as any).execute(APPLY_COMMAND, ctx);

  return { ...ctx.result, warnings: layout.warnings };
}
